Attribute VB_Name = "modInvoice"
Option Explicit

' ==============================================================================
' Module: modInvoice.bas — Invoice lifecycle (NO PROTECTION)
'
' ACTUAL Invoice_Template cell map (from Plan A):
'   B8  = Invoice Number
'   B9  = Date
'   B10 = Due Date
'   B11 = Terms
'   E9  = Customer Name
'   E10 = Customer Address
'   E11 = Customer Tax ID
'   A15:H29 = Line Items (15 rows)
'   H31 = Subtotal
'   H33 = Tax
'   H35 = Grand Total
' ==============================================================================

' --------------------------------------------------------------------------
' 1. GenerateInvoice() — PRIMARY ENTRY POINT
' --------------------------------------------------------------------------
Public Sub GenerateInvoice()
    On Error GoTo ErrHandler
    
    modUtilities.TogglePerformance True
    ClearInvoiceTemplate
    
    Dim wsInv As Worksheet
    Set wsInv = modUtilities.SafeSheetRef("Invoice_Template")
    
    ' Set Invoice Number
    Dim invNo As String
    invNo = modNumbering.GetNextInvoiceNumber()
    wsInv.Range("B8").Value = invNo
    
    ' Set Date and Due Date
    wsInv.Range("B9").Value = Date
    wsInv.Range("B10").Value = Date + 30
    wsInv.Range("B11").Value = modUtilities.GetSetting("Payment Terms")

    ' Update Logo from Settings
    UpdateLogo wsInv
    
    modUtilities.TogglePerformance False
    
    ' Select Customer
    modCustomer.ShowCustomerSelector
    If modCustomer.g_selectedCustomerID = "" Then
        MsgBox "Invoice creation cancelled.", vbInformation
        Exit Sub
    End If
    
    ' Populate Customer
    modCustomer.PopulateInvoiceCustomer modCustomer.g_selectedCustomerID
    
    ' Add Products
    modProduct.ShowProductSelector
    
    ' Show Preview
    wsInv.Activate
    
    ' Confirmation
    If MsgBox("Finalize this invoice?", vbYesNo + vbQuestion, "Finalize Invoice") = vbYes Then
        FinalizeInvoice
    End If
    Exit Sub
ErrHandler:
    modUtilities.TogglePerformance False
    modUtilities.ErrorHandler "GenerateInvoice", Err.Number, Err.Description
End Sub

' --------------------------------------------------------------------------
' 2. FinalizeInvoice() — Saves to Transactions
' --------------------------------------------------------------------------
Public Sub FinalizeInvoice()
    On Error GoTo ErrHandler
    
    Dim wsInv As Worksheet
    Set wsInv = modUtilities.SafeSheetRef("Invoice_Template")
    Dim wsTrans As Worksheet
    Set wsTrans = modUtilities.SafeSheetRef("Transactions")
    
    ' Validate
    If wsInv.Range("B8").Value = "" Then MsgBox "Invoice number missing!", vbCritical: Exit Sub
    If wsInv.Range("E9").Value = "" Then MsgBox "Customer missing!", vbCritical: Exit Sub
    If Val(wsInv.Range("H35").Value) <= 0 Then MsgBox "Total must be > 0.", vbCritical: Exit Sub
    
    modUtilities.TogglePerformance True
    
    ' Read from template
    Dim invNo As String:     invNo = CStr(wsInv.Range("B8").Value)
    Dim custName As String:  custName = CStr(wsInv.Range("E9").Value)
    Dim dateIssued As Date:  dateIssued = wsInv.Range("B9").Value
    Dim due As Date:         due = wsInv.Range("B10").Value
    Dim subTot As Double:    subTot = Val(wsInv.Range("H31").Value)
    Dim tax As Double:       tax = Val(wsInv.Range("H33").Value)
    Dim total As Double:     total = Val(wsInv.Range("H35").Value)
    
    ' Customer ID lookup
    Dim custData As Object
    Set custData = modCustomer.LookupCustomer(custName)
    Dim custID As String
    If Not custData Is Nothing Then custID = custData("ID") Else custID = "UNKNOWN"
    
    ' Write to Transactions
    Dim nextRow As Long
    nextRow = modUtilities.GetNextRow(wsTrans, 1)
    
    With wsTrans
        .Cells(nextRow, 1).Value = invNo
        .Cells(nextRow, 2).Value = custID
        .Cells(nextRow, 3).Value = custName
        .Cells(nextRow, 4).Value = dateIssued
        .Cells(nextRow, 5).Value = due
        .Cells(nextRow, 6).Value = subTot
        .Cells(nextRow, 7).Value = tax
        .Cells(nextRow, 8).Value = 0
        .Cells(nextRow, 9).Value = total
        .Cells(nextRow, 10).Value = 0
        .Cells(nextRow, 11).Value = total
        .Cells(nextRow, 12).Value = "Pending"
        .Cells(nextRow, 13).Value = modUtilities.GetSetting("Jurisdiction")
        .Cells(nextRow, 14).Value = "Standard"
        .Cells(nextRow, 15).Value = "Generated by System"
    End With
    
    modUtilities.AuditLog "INVOICE_CREATED", invNo & " for " & modUtilities.FormatCurrency(total)
    modUtilities.TogglePerformance False
    MsgBox "Invoice " & invNo & " created!", vbInformation
    
    If MsgBox("Export to PDF?", vbYesNo + vbQuestion) = vbYes Then
        modExport.ExportToPDF "invoice", invNo
    End If
    Exit Sub
ErrHandler:
    modUtilities.TogglePerformance False
    modUtilities.ErrorHandler "FinalizeInvoice", Err.Number, Err.Description
End Sub

' --------------------------------------------------------------------------
' 3. ClearInvoiceTemplate()
' --------------------------------------------------------------------------
Public Sub ClearInvoiceTemplate()
    On Error GoTo ErrHandler
    Dim wsInv As Worksheet
    Set wsInv = modUtilities.SafeSheetRef("Invoice_Template")
    
    modUtilities.UnprotectSheet wsInv.Name
    
    On Error Resume Next
    wsInv.Range("B8").ClearContents    ' Invoice Number
    wsInv.Range("B9").ClearContents    ' Date
    wsInv.Range("B10").ClearContents   ' Due Date
    ' rngPaymentTerms mapped to B11 in Plan A
    wsInv.Range("B11").ClearContents
    ' Customer info E9:E11
    wsInv.Range("E9:E11").ClearContents
    ' Only clear data columns A-G, preserve H column formulas
    wsInv.Range("A15:G29").ClearContents
    ' H33 (tax) is set by VBA, safe to clear
    wsInv.Range("H33").ClearContents
    ' DO NOT touch H15:H29 (line total formulas)
    ' DO NOT touch H31 (=SUM formula)
    ' DO NOT touch H35 (=GRAND TOTAL formula)
    On Error GoTo 0
    
    modUtilities.ProtectSheet wsInv.Name
    Exit Sub
ErrHandler:
    modUtilities.ProtectSheet wsInv.Name
    modUtilities.ErrorHandler "ClearInvoiceTemplate", Err.Number, Err.Description
End Sub

' --------------------------------------------------------------------------
' 4. EditInvoice(invoiceNo)
' --------------------------------------------------------------------------
Public Sub EditInvoice(invoiceNo As String)
    On Error GoTo ErrHandler
    Dim wsTrans As Worksheet
    Set wsTrans = modUtilities.SafeSheetRef("Transactions")
    Dim foundRow As Long: foundRow = 0
    Dim i As Long
    For i = 2 To wsTrans.Cells(wsTrans.Rows.Count, 1).End(xlUp).Row
        If CStr(wsTrans.Cells(i, 1).Value) = invoiceNo Then foundRow = i: Exit For
    Next i
    If foundRow = 0 Then MsgBox "Invoice not found.", vbExclamation: Exit Sub
    
    ClearInvoiceTemplate
    Dim wsInv As Worksheet
    Set wsInv = modUtilities.SafeSheetRef("Invoice_Template")
    wsInv.Range("B8").Value = wsTrans.Cells(foundRow, 1).Value
    wsInv.Range("B9").Value = wsTrans.Cells(foundRow, 4).Value
    wsInv.Range("B10").Value = wsTrans.Cells(foundRow, 5).Value
    modCustomer.PopulateInvoiceCustomer CStr(wsTrans.Cells(foundRow, 2).Value)
    wsInv.Activate
    MsgBox "Invoice loaded. Re-enter line items.", vbInformation
    Exit Sub
ErrHandler:
    modUtilities.ErrorHandler "EditInvoice", Err.Number, Err.Description
End Sub

' --------------------------------------------------------------------------
' 5. CancelInvoice(invoiceNo)
' --------------------------------------------------------------------------
Public Sub CancelInvoice(invoiceNo As String)
    On Error GoTo ErrHandler
    Dim wsTrans As Worksheet
    Set wsTrans = modUtilities.SafeSheetRef("Transactions")
    Dim i As Long
    For i = 2 To wsTrans.Cells(wsTrans.Rows.Count, 1).End(xlUp).Row
        If CStr(wsTrans.Cells(i, 1).Value) = invoiceNo Then
            wsTrans.Cells(i, 12).Value = "Cancelled"
            wsTrans.Cells(i, 11).Value = 0
            modUtilities.AuditLog "INVOICE_CANCELLED", invoiceNo
            MsgBox "Invoice cancelled.", vbInformation
            Exit Sub
        End If
    Next i
    MsgBox "Invoice not found.", vbExclamation
    Exit Sub
ErrHandler:
    modUtilities.ErrorHandler "CancelInvoice", Err.Number, Err.Description
End Sub

' --------------------------------------------------------------------------
' Helper: Update Logo from Settings
' --------------------------------------------------------------------------
Public Sub UpdateLogo(ws As Worksheet)
    ' Remove On Error Resume Next to catch errors
    On Error GoTo ErrHandler
    
    ' Handle protection locally since this can be called from Activate event
    modUtilities.UnprotectSheet ws.Name
    
    Dim picPath As String
    picPath = modUtilities.GetSetting("Logo Path")
    
    ' Strip quotes and trim
    picPath = Replace(picPath, """", "")
    picPath = Trim(picPath)
    
    ' Log what we found
    modUtilities.AuditLog "UPDATE_LOGO", "Path=" & picPath
    
    ' Remove old logo
    Dim shp As Shape
    For Each shp In ws.Shapes
        If shp.Name = "CompanyLogo" Then shp.Delete
    Next shp
    
    If picPath = "" Then
        modUtilities.ProtectSheet ws.Name
        Exit Sub
    End If
    
    If Dir(picPath) = "" Then
        MsgBox "Warning: Logo file not found at:" & vbCrLf & picPath & vbCrLf & vbCrLf & _
               "Please check the path in Settings.", vbExclamation, "Logo Error"
        modUtilities.ProtectSheet ws.Name
        Exit Sub
    End If
    
    ' ... (Previous code for getting path and removing old logo) ...
    
    ' Target correct logo area (A1:C5 is merged in template)
    Dim logoRange As Range
    Set logoRange = ws.Range("A1:C5")
    
    ' Use AddPicture
    Dim p As Shape
    Set p = ws.Shapes.AddPicture(picPath, msoFalse, msoTrue, logoRange.Left, logoRange.Top, -1, -1)
    
    With p
        .Name = "CompanyLogo"
        .LockAspectRatio = msoTrue
        
        ' 1. Reset to original size (just in case)
        .ScaleHeight 1, msoTrue
        .ScaleWidth 1, msoTrue
        
        ' 2. Calculate Max Dimensions (leaving 5px padding)
        Dim maxHeight As Double, maxWidth As Double
        maxHeight = logoRange.Height - 10
        maxWidth = logoRange.Width - 10
        
        ' 3. Scale down if needed
        If .Height > maxHeight Then .Height = maxHeight
        If .Width > maxWidth Then .Width = maxWidth
        
        ' 4. Center in Range
        .Left = logoRange.Left + (logoRange.Width - .Width) / 2
        .Top = logoRange.Top + (logoRange.Height - .Height) / 2
    End With
    
    ' Clear the "[LOGO]" text if it exists so it doesn't show behind transparent images
    logoRange.Value = ""
    
    modUtilities.ProtectSheet ws.Name
    Exit Sub
ErrHandler:
    modUtilities.ProtectSheet ws.Name
    MsgBox "Error inserting logo: " & Err.Description & vbCrLf & "Path: " & picPath, vbCritical, "Logo Error"
End Sub
